### PR TITLE
Website is now responsive

### PR DESCRIPTION
**Pull request by harsh-kumar213**
The whole website is now responsive.
I did it by using media queries and defining the sizes by suitable method.
For tablets
Screenshot (74)

For mobile
Screenshot (73)

### CODE REVIEW

**Comment by piug-07** [comment]
It's not responsive. Checkout our design then change accordingly.

**Comment by harsh-kumar213** [comment]
I made some changes in the design of the website which would suit the dimensions better

**Comment by harsh-kumar213** [comment]
> It's not responsive. Checkout our design then change accordingly.

Can you tell which section is not responding because it is completely responsive in my device

**Comment by piug-07** [comment]
Will you pls first checkout Figma design,  then change according to it

**Comment by harsh-kumar213** [comment]
okk i will change it accroding to it

**Comment by piug-07** [comment]
You have to pull all the changes first then pull it again there are conflicts in the PR and also remove the box effect and design the pages according to figma file.

**Comment by harsh-kumar213** [comment]
Ok will do it as soon as possible.

**Pull request closed without merging**
