### PR TITLE
Removes undefined #259 

### PR DESCRIPTION
**Pull request by Shrejal123**
I have fix this issue . Please merge it .

### CODE REVIEW

**Comment by piug-07** [comment]
You have to pull the all changes of the application then again create PR

**Comment by Shrejal123** [comment]
@piug-07 what you wants to say I don't understand please tell me.

**Comment by piug-07** [comment]
sync the repo then again create the PR

**Comment by Shrejal123** [comment]
@piug-07 I have sync the repo. Please merge it.

**Comment by Shrejal123** [comment]
@piug-07 Please merge it, i have already sync the repo.

**Comment by Shrejal123** [comment]
@piug-07 if there will be any error in this Please tell me i will try to fix it and if not please merge it in main code.
Thanku.

**Comment by piug-07** [comment]
You have to pull all the changes and then again create the PR it will be merged surely.

**Pull request closed without merging**
