### PR TITLE
Dark theme will remain constant when we switch from one web page to the other [GSSoC'23]

### PR DESCRIPTION
**Pull request by thevirengarg**
if I am browsing in the dark theme and I am at the "All" web page and then I click on "technology" to go to that web page then my theme automatically gets back to default which is the light theme. I solved this issue so that, while going from one web page to the other the theme of the website remains constant. if a user is browsing in a dark theme it remains in the dark theme instead changing itself back to light theme mode.[GSSoC'23]. My issue no #322

### CODE REVIEW

**Comment by thevirengarg** [comment]
@piug-07 Please review this PR and mark it under gssoc'23

**Comment by piug-07** [comment]
It's not working. Check once again

**Comment by thevirengarg** [comment]
@piug-07 I have updated it please review it once again.

**Comment by piug-07** [comment]
It's not working dude check it once again and then create again PR

**Pull request closed without merging**
