### PR TITLE
scrollbar changed2

### PR DESCRIPTION
**Pull request by Shreyans2004**
I have changed the styling of  scrollbar,so that it now matches with the website's color and removed the hover effect (of orange color)which was previously added by me in  #385 .Can it be merged now?

### CODE REVIEW

**Comment by piug-07** [comment]
Apply scrollbar bar in blog page also

**Comment by Shreyans2004** [comment]
Done .The scrollbar Styling has been done in blog page also.

**Comment by piug-07** [comment]
But you can mismanage the content of a blog page  check first then again create a PR

**Comment by Shreyans2004** [comment]
Now the issue is resolved.Can it be merge now?

**Comment by piug-07** [comment]
nyc good job!

**Pull request merged**
