### PR TITLE
Added `openAI-GPT v3.5` in ChatBot

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
## Description
Hello @piug-07   ,
I have added Chat Bot using API of Chat GPT v3.5
It is working smoothly and answering all the questions.

### Instructions -
1. Visit to this website - https://rapidapi.com/Glavier/api/chatgpt53
2. Subscribe the `API` // important step without this API will not work, also this API is free of cost.
3. See the right side of the page :-
image
4. Copy the API key and paste in the key in the chatbot/script.js

## Screenshot - 
image

## Checklist

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by piug-07** [comment]
Chatbot is not working properly, check it again.

**Comment by SyedImtiyaz-1** [comment]
> Chatbot is not working properly, check it again.

Have you enter the api key ?

**Comment by SyedImtiyaz-1** [comment]
@piug-07 ,
Bcz without api key it won't work.

**Comment by SyedImtiyaz-1** [comment]
Hello @piug-07  ,
1. Visit this website - https://rapidapi.com/Glavier/api/chatgpt53 
2. Subscribe the API (I have already subscribed and subscribe will free of cost)
3. After subscribing do same as I did in the video and copy the whole API_KEY and paste it into the chatbot/script.js code 

[Screencast from 29-06-23 06:52:36 PM IST.webm](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/121503426/ab4b0829-69e9-4ae8-8d92-b247873a4e09)

### Screenshot - 
Screenshot from 2023-06-29 18-55-13

- You have to paste the code in the **API KEY** empty object where I have mentioned **// IMPORTANT**

**Comment by SyedImtiyaz-1** [comment]
@piug-07 ,
He  is not even a member of GSSoC 23 he is just spammer this stuff for lose ranking.
Ask his details before taking actions.

**Comment by SyedImtiyaz-1** [comment]
Thank you @piug-07 .
He is trolling each and everyone in GSSoC 23 we are really tired of him.

**Comment by piug-07** [comment]
You can add your own API key in it. It's not free in my account

**Comment by SyedImtiyaz-1** [comment]
> You can add your own API key in it. It's not free in my account

okay adding now

**Pull request merged**
