### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by parasss19**
Hi sir 
Applied the Dark Mode  #132

### CODE REVIEW

**Comment by HarshSharma0801** [comment]
buttons in section-1 disappear , review your code properly

**Comment by parasss19** [comment]
> buttons in section-1 disappear , review your code properly

i sloved the issues pls review once

**Comment by piug-07** [comment]
Apply the dark mode on both the pages and also check the UI once all are looking fine.

**Comment by parasss19** [comment]
> Apply the dark mode on both the pages and also check the UI once all are looking fine.

Hii @piug-07  I will start working on it
Please assign this issue to me

**Comment by parasss19** [comment]
Hii @HarshSharma0801 
U resolved the issue #132 ? Or should I start working on it

**Comment by parasss19** [comment]
> Apply the dark mode on both the pages and also check the UI once all are looking fine.
Hi @piug-07  
I didn't understand about second page can u elaborate it

**Comment by HarshSharma0801** [comment]
@piug-07 can you review my PR please?

**Comment by HarshSharma0801** [comment]
as I have completed this issue

**Comment by HarshSharma0801** [comment]
@parasss19  yes but you haven't requested pull request yet

**Comment by parasss19** [comment]
> @parasss19 yes but you haven't requested pull request yet and you have conflicts also in other one

@HarshSharma0801 You are not able to see my PR?

**Comment by HarshSharma0801** [comment]
@parasss19  it has conflicts so it can't be merged

**Comment by parasss19** [comment]
Hi @piug-07 
I Applied the Dark Mode on both screens

# Features
1 I have designed the slide button for dark mode
2 I include transition of 0.2 seconds linear so that you can see the transition
3 After toggle every text is visible 
4 I didnt change the color of text on your website . Its toggle automatically on the basis of light mode or dark mode

# Screen 1
https://github.com/DSC-JSS-NOIDA/blogzen/assets/101205226/5414fd17-d38d-456d-9993-9f0172de110d

# Screen 2

https://github.com/DSC-JSS-NOIDA/blogzen/assets/101205226/c8f0c873-0d9a-4a2d-b1bc-1e0d2d84510c

**Comment by parasss19** [comment]
> @parasss19 it has conflicts so it can't be merged

I resolved the conflicts

**Pull request closed without merging**
